"""Add Sections Table

Revision ID: 5134934c83ea
Revises: b4dc8ade24bb
Create Date: 2020-05-19 19:31:06.503974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5134934c83ea'
down_revision = 'b4dc8ade24bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair_reports_grade',
    sa.Column('campus', sa.Enum('UBCV', 'UBCO', name='campusenum'), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('session', sa.Enum('W', 'S', name='sessionenum'), nullable=False),
    sa.Column('subject', sa.String(length=4), nullable=False),
    sa.Column('course', sa.String(length=3), nullable=False),
    sa.Column('detail', sa.String(length=3), nullable=False),
    sa.Column('section', sa.String(length=7), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('educators', sa.String(), nullable=True),
    sa.Column('enrolled', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('stdev', sa.Float(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('num_pass', sa.Integer(), nullable=True),
    sa.Column('num_fail', sa.Integer(), nullable=True),
    sa.Column('withdrew', sa.Integer(), nullable=True),
    sa.Column('audit', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('grade_0_9', sa.Integer(), nullable=True),
    sa.Column('grade_10_19', sa.Integer(), nullable=True),
    sa.Column('grade_20_29', sa.Integer(), nullable=True),
    sa.Column('grade_30_39', sa.Integer(), nullable=True),
    sa.Column('grade_40_49', sa.Integer(), nullable=True),
    sa.Column('grade_lt50', sa.Integer(), nullable=True),
    sa.Column('grade_50_54', sa.Integer(), nullable=True),
    sa.Column('grade_55_59', sa.Integer(), nullable=True),
    sa.Column('grade_60_63', sa.Integer(), nullable=True),
    sa.Column('grade_64_67', sa.Integer(), nullable=True),
    sa.Column('grade_68_71', sa.Integer(), nullable=True),
    sa.Column('grade_72_75', sa.Integer(), nullable=True),
    sa.Column('grade_76_79', sa.Integer(), nullable=True),
    sa.Column('grade_80_84', sa.Integer(), nullable=True),
    sa.Column('grade_85_89', sa.Integer(), nullable=True),
    sa.Column('grade_90_100', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('campus', 'year', 'session', 'subject', 'course', 'detail', 'section')
    )
    op.create_table('subjects',
    sa.Column('campus', sa.Enum('UBCV', 'UBCO', name='campusenum'), nullable=False),
    sa.Column('subject', sa.String(length=4), nullable=False),
    sa.Column('subject_title', sa.String(), nullable=True),
    sa.Column('faculty_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('campus', 'subject')
    )
    op.create_table('tableau_dashboard_grade',
    sa.Column('campus', sa.Enum('UBCV', 'UBCO', name='campusenum'), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('session', sa.Enum('W', 'S', name='sessionenum'), nullable=False),
    sa.Column('subject', sa.String(length=4), nullable=False),
    sa.Column('course', sa.String(length=3), nullable=False),
    sa.Column('detail', sa.String(length=3), nullable=False),
    sa.Column('section', sa.String(length=7), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('educators', sa.String(), nullable=True),
    sa.Column('enrolled', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('stdev', sa.Float(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('grade_lt50', sa.Integer(), nullable=True),
    sa.Column('grade_50_54', sa.Integer(), nullable=True),
    sa.Column('grade_55_59', sa.Integer(), nullable=True),
    sa.Column('grade_60_63', sa.Integer(), nullable=True),
    sa.Column('grade_64_67', sa.Integer(), nullable=True),
    sa.Column('grade_68_71', sa.Integer(), nullable=True),
    sa.Column('grade_72_75', sa.Integer(), nullable=True),
    sa.Column('grade_76_79', sa.Integer(), nullable=True),
    sa.Column('grade_80_84', sa.Integer(), nullable=True),
    sa.Column('grade_85_89', sa.Integer(), nullable=True),
    sa.Column('grade_90_100', sa.Integer(), nullable=True),
    sa.Column('subject_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subject_title'], ['subjects.subject_title'], ),
    sa.PrimaryKeyConstraint('campus', 'year', 'session', 'subject', 'course', 'detail', 'section')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tableau_dashboard_grade')
    op.drop_table('subjects')
    op.drop_table('pair_reports_grade')
    # ### end Alembic commands ###
