"""empty message

Revision ID: e6718ea6e458
Revises: 5134934c83ea
Create Date: 2020-05-19 19:35:17.525850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6718ea6e458'
down_revision = '5134934c83ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tableau_dashboard_grade', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tableau_dashboard_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=4), nullable=False))

    # ### end Alembic commands ###
